version: '3.0'
services:
  chatbot:
    image: khalosa/rasa-aarch64:3.5.2
    container_name: chatbot
    ports:
      - '5005:5005'
    volumes:
      - ./:/app
    command: run

  chatbot-actions:
    image: rasa/rasa-sdk:latest
    container_name: chatbot-actions
    platform: linux/amd64
    ports:
      - '5055:5055'
    volumes:
      - ./actions:/app/actions

  bot:
    build: .
    container_name: "bot"
    environment:
      - BOT_TOKEN=<REPLACE_HERE>
